###
GET http://localhost:3333/memories HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ1bm8gRmVybmFuZGVzIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzQzNzkzNTkyP3Y9NCIsInN1YiI6ImRmZDViNDg5LWUwZTMtNDVmNC04YWE1LTcyNTI3NTQ5YzAwNCIsImlhdCI6MTcwODMyNTE3MywiZXhwIjoxNzA4NDExNTczfQ.MXolIIeSkjmmdQTCAZLLOWRhBYLXTFZ5a1x5zkNCOvg

###
GET http://localhost:3333/memories/5842f4c8-b493-4036-a81f-847fef0398af HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ1bm8gRmVybmFuZGVzIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzQzNzkzNTkyP3Y9NCIsInN1YiI6ImRmZDViNDg5LWUwZTMtNDVmNC04YWE1LTcyNTI3NTQ5YzAwNCIsImlhdCI6MTcwODMyNTE3MywiZXhwIjoxNzA4NDExNTczfQ.MXolIIeSkjmmdQTCAZLLOWRhBYLXTFZ5a1x5zkNCOvg

###
POST http://localhost:3333/memories HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ1bm8gRmVybmFuZGVzIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzQzNzkzNTkyP3Y9NCIsInN1YiI6ImRmZDViNDg5LWUwZTMtNDVmNC04YWE1LTcyNTI3NTQ5YzAwNCIsImlhdCI6MTcwODMyNTE3MywiZXhwIjoxNzA4NDExNTczfQ.MXolIIeSkjmmdQTCAZLLOWRhBYLXTFZ5a1x5zkNCOvg

{
  "content": "Conteudo teste",
  "coverUrl": "https://github.com/SkyHeads.png",
  "isPublic": 1
}

###
PUT http://localhost:3333/memories/5842f4c8-b493-4036-a81f-847fef0398af HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ1bm8gRmVybmFuZGVzIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzQzNzkzNTkyP3Y9NCIsInN1YiI6ImRmZDViNDg5LWUwZTMtNDVmNC04YWE1LTcyNTI3NTQ5YzAwNCIsImlhdCI6MTcwODMyNTE3MywiZXhwIjoxNzA4NDExNTczfQ.MXolIIeSkjmmdQTCAZLLOWRhBYLXTFZ5a1x5zkNCOvg

{
  "content": "oi",
  "coverUrl": "https://github.com/SkyHeads.png",
  "isPublic": 1
}

###
DELETE http://localhost:3333/memories/5842f4c8-b493-4036-a81f-847fef0398af HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ1bm8gRmVybmFuZGVzIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzQzNzkzNTkyP3Y9NCIsInN1YiI6ImRmZDViNDg5LWUwZTMtNDVmNC04YWE1LTcyNTI3NTQ5YzAwNCIsImlhdCI6MTcwODMyNTE3MywiZXhwIjoxNzA4NDExNTczfQ.MXolIIeSkjmmdQTCAZLLOWRhBYLXTFZ5a1x5zkNCOvg

###
POST http://localhost:3333/register HTTP/1.1
Content-Type: application/json

{
  "code": "59e631d483a9946edf77"
}